DROP DATABASE IF EXISTS HABIUS;
DROP DATABASE IF EXISTS SISTEMAADVOCACIA;

CREATE DATABASE IF NOT EXISTS HABIUS;

USE HABIUS;

CREATE TABLE MOV_MOVIMENTACAO (
  MOV_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  MOV_MOVIMENTACAO VARCHAR(50) NULL,
  PRIMARY KEY(MOV_CODIGO)
);

CREATE TABLE POS_POSICAOCLIENTE (
  POS_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  POS_POSICAO VARCHAR(50) NULL,
  PRIMARY KEY(POS_CODIGO)
);

CREATE TABLE ECI_ESTADOCIVIL (
  ECI_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ECI_DESCRICAO VARCHAR(100) NULL,
  PRIMARY KEY(ECI_CODIGO)
);

CREATE TABLE NIV_NIVEL (
  NIV_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  NIV_DESCRICAO VARCHAR(100) NULL,
  PRIMARY KEY(NIV_CODIGO)
);

CREATE TABLE MSG_MENSAGEM (
  MSG_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  MSG_MENSAGEM TEXT(500) NULL,
  MSG_DATAMENSAGEM DATETIME NULL,
  PRIMARY KEY(MSG_CODIGO)
);

CREATE TABLE EST_ESTADO (
  EST_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  EST_ESTADO VARCHAR(100) NOT NULL,
  EST_SIGLA VARCHAR(2) NOT NULL,
  PRIMARY KEY(EST_CODIGO)
);

CREATE TABLE TRI_TRIBUNAL (
  TRI_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  TRI_TRIBUNAL VARCHAR(50) NULL,
  PRIMARY KEY(TRI_CODIGO)
);

CREATE TABLE VAR_VARA (
  VAR_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  VAR_VARA VARCHAR(50) NULL,
  PRIMARY KEY(VAR_CODIGO)
);

CREATE TABLE SEV_SERVICO (
  SEV_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  SEV_SERVICO VARCHAR(200) NULL,
  PRIMARY KEY(SEV_CODIGO)
);

CREATE TABLE TID_TIPODESPESA (
  TID_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  TID_TIPODESPESA VARCHAR(200) NULL,
  TID_CATEGORIA TINYINT(1) NULL,
  PRIMARY KEY(TID_CODIGO)
);

CREATE TABLE CON_CONTATO (
  CON_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_CODIGO INTEGER(11) UNSIGNED NULL,
  CON_NOME VARCHAR(150) NULL,
  CON_CELULAR VARCHAR(20) NULL,
  CON_TELEFONE VARCHAR(20) NULL,
  CON_EMAIL VARCHAR(100) NULL,
  PRIMARY KEY(CON_CODIGO)
);

CREATE TABLE CLA_CLASSE (
  CLA_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  CLA_CLASSE VARCHAR(50) NULL,
  PRIMARY KEY(CLA_CODIGO)
);

CREATE TABLE ASS_ASSUNTO (
  ASS_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ASS_ASSUNTO VARCHAR(50) NULL,
  PRIMARY KEY(ASS_CODIGO)
);

CREATE TABLE CAM_CAMARA (
  CAM_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  CAM_CAMARA VARCHAR(50) NULL,
  PRIMARY KEY(CAM_CODIGO)
);

CREATE TABLE CID_CIDADE (
  CID_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  CID_CIDADE VARCHAR(100) NOT NULL,
  EST_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PRIMARY KEY(CID_CODIGO),
 FOREIGN KEY(EST_CODIGO)
    REFERENCES EST_ESTADO(EST_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE END_ENDERECO (
  END_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  CID_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  END_LOGRADOURO VARCHAR(200) NULL,
  END_NUMERO VARCHAR(8) NULL,
  END_COMPLEMENTO VARCHAR(8) NULL,
  END_BAIRRO VARCHAR(100) NULL,
  END_CEP VARCHAR(20) NULL,
  PRIMARY KEY(END_CODIGO),
  FOREIGN KEY(CID_CODIGO)
    REFERENCES CID_CIDADE(CID_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE REC_RECURSO (
  REC_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  TRI_CODIGO INTEGER(11) UNSIGNED NULL,
  CAM_CODIGO INTEGER(11) UNSIGNED NULL,
  PRIMARY KEY(REC_CODIGO),
  FOREIGN KEY(CAM_CODIGO)
    REFERENCES CAM_CAMARA(CAM_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(TRI_CODIGO)
    REFERENCES TRI_TRIBUNAL(TRI_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE PES_PESSOA (
  PES_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  CON_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  ECI_CODIGO INTEGER(11) UNSIGNED NULL,
  NIV_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  END_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PES_LOGIN VARCHAR(50) BINARY NOT NULL,
  PES_SENHA VARCHAR(255) BINARY NOT NULL,
  PES_SEXO VARCHAR(1) NULL,
  PES_DATACADASTRO DATE NOT NULL,
  PES_ATIVO TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PES_CNPJ VARCHAR(20) NULL,
  PES_CPF VARCHAR(15) NULL,
  PES_RG VARCHAR(20) NULL,
  PES_DATANASCIMENTO DATE NULL,
  PES_OAB VARCHAR(10) NULL,
  PRIMARY KEY(PES_CODIGO),
   FOREIGN KEY(END_CODIGO)
    REFERENCES END_ENDERECO(END_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(NIV_CODIGO)
    REFERENCES NIV_NIVEL(NIV_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(CON_CODIGO)
    REFERENCES CON_CONTATO(CON_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
   FOREIGN KEY(ECI_CODIGO)
    REFERENCES ECI_ESTADOCIVIL(ECI_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE PRO_PROCESSO (
  PRO_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  VAR_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  CID_CODIGO_COMARCA INTEGER(11) UNSIGNED NOT NULL,
  CLA_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  POS_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  REC_CODIGO INTEGER(11) UNSIGNED NULL,
  ASS_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PRO_DATACRIACAO DATETIME NULL,
  PRO_NUMEROPROCESSO VARCHAR(30) NULL,
  PRO_DESCRICAO VARCHAR(200) NULL,
  PRO_OBSERVACAO TEXT NULL,
  PRIMARY KEY(PRO_CODIGO),
  FOREIGN KEY(ASS_CODIGO)
    REFERENCES ASS_ASSUNTO(ASS_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(REC_CODIGO)
    REFERENCES REC_RECURSO(REC_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(CLA_CODIGO)
    REFERENCES CLA_CLASSE(CLA_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(CID_CODIGO_COMARCA)
    REFERENCES CID_CIDADE(CID_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(VAR_CODIGO)
    REFERENCES VAR_VARA(VAR_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(POS_CODIGO)
    REFERENCES POS_POSICAOCLIENTE(POS_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE SIT_SITE (
  SIT_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_CODIGO_ADV INTEGER(11) UNSIGNED NOT NULL,
  SIT_SITE VARCHAR(200) NULL,
  SIT_DESCRICAO VARCHAR(200) NULL,
  PRIMARY KEY(SIT_CODIGO),
 FOREIGN KEY(PES_CODIGO_ADV)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE FEE_FEEDBACK (
  FEE_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_CODIGO_CLI INTEGER(11) UNSIGNED NOT NULL,
  FEE_FEEDBACK VARCHAR(250) NULL,
  FEE_NOTA TINYINT(2) UNSIGNED NULL,
  PRIMARY KEY(FEE_CODIGO),
  FOREIGN KEY(PES_CODIGO_CLI)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE AGE_AGENDA (
  AGE_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_CODIGO_ADV INTEGER(11) UNSIGNED NOT NULL,
  AGE_TITULO VARCHAR(50) NULL,
  AGE_DESCRICAO VARCHAR(250) NULL,
  AGE_DATACRIACAO DATETIME NULL,
  AGE_DATAFINALIZACAO DATETIME NULL,
  AGE_FINALIZADO TINYINT(1) UNSIGNED NULL,
  PRIMARY KEY(AGE_CODIGO),
 FOREIGN KEY(PES_CODIGO_ADV)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE APR_ADVOGADO_PROCESSO (
  PRO_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PES_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  FOREIGN KEY(PES_CODIGO)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE SEP_SERVICOS_PESSOA (
  SEV_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PES_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  HON_VALOR DECIMAL(10,2) NULL,
  PRIMARY KEY(SEV_CODIGO, PES_CODIGO),
  FOREIGN KEY(SEV_CODIGO)
    REFERENCES SEV_SERVICO(SEV_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE CPR_CLIENTE_PROCESSO (
  PES_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PRO_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  FOREIGN KEY(PES_CODIGO)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE PMV_PROCESSO_MOVIMENTACAO (
  PMV_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRO_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  MOV_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PMV_DATA_MOVIMENTACAO DATE NOT NULL,
  PMV_FINALIZADO TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY(PMV_CODIGO, PRO_CODIGO, MOV_CODIGO),
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(MOV_CODIGO)
    REFERENCES MOV_MOVIMENTACAO(MOV_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE CMS_CLIENTE_MENSAGEM (
  PES_CODIGO_ADVOGADO_RECEBE INTEGER(11) UNSIGNED NOT NULL,
  PES_CODIGO_CLIENTE_ENVIA INTEGER(11) UNSIGNED NOT NULL,
  MSG_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  FOREIGN KEY(MSG_CODIGO)
    REFERENCES MSG_MENSAGEM(MSG_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_CLIENTE_ENVIA)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_ADVOGADO_RECEBE)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE AMS_ADVOGADO_MENSAGEM (
  MSG_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PES_CODIGO_CLIENTE_RECEBE INTEGER(11) UNSIGNED NOT NULL,
  PES_CODIGO_ADVOGADO_ENVIA INTEGER(11) UNSIGNED NOT NULL,
  FOREIGN KEY(MSG_CODIGO)
    REFERENCES MSG_MENSAGEM(MSG_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_ADVOGADO_ENVIA)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_CLIENTE_RECEBE)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE DAP_DATAPROCESSO (
  DAP_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  DAP_DATAAUDIENCIA DATETIME NULL,
  PRO_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PRIMARY KEY(DAP_CODIGO),
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);


CREATE TABLE PAG_PAGAMENTO (
  PAG_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PES_CODIGO_ADV INTEGER(11) UNSIGNED NOT NULL,
  PRO_CODIGO INTEGER(11) UNSIGNED NULL,
  PES_CODIGO_CLI INTEGER(11) UNSIGNED NULL,
  SEV_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PAG_VALOR DECIMAL(10,2) NULL,
  PAG_DATAPAGAMENTO DATETIME NULL,
  PAG_OBS VARCHAR(200) NULL,
  PRIMARY KEY(PAG_CODIGO),
  FOREIGN KEY(SEV_CODIGO)
    REFERENCES SEV_SERVICO(SEV_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_ADV)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_CLI)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

CREATE TABLE DES_DESPESA (
  DES_CODIGO INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  TID_CODIGO INTEGER(11) UNSIGNED NOT NULL,
  PRO_CODIGO INTEGER(11) UNSIGNED NULL,
  PES_CODIGO_ADV INTEGER(11) UNSIGNED NOT NULL,
  DES_DATA DATE NOT NULL,
  DES_VALOR DECIMAL(10,2) NULL,
  DES_OBS VARCHAR(200) NULL,
  PRIMARY KEY(DES_CODIGO),
 FOREIGN KEY(TID_CODIGO)
    REFERENCES TID_TIPODESPESA(TID_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PES_CODIGO_ADV)
    REFERENCES PES_PESSOA(PES_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PRO_CODIGO)
    REFERENCES PRO_PROCESSO(PRO_CODIGO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
);

ALTER TABLE HABIUS.CON_CONTATO 
  ADD FOREIGN KEY (PES_CODIGO) 
    REFERENCES HABIUS.PES_PESSOA (PES_CODIGO) 
    ON DELETE RESTRICT
    ON UPDATE CASCADE
;
USE HABIUS;